# .readthedocs.yaml - MINIMAL CONFIG
# Read the Docs configuration file

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.9"

# All other configurations (like specific paths for conf.py, doc_dir, requirements.txt,
# or build jobs) will be handled in the Read the Docs web UI.